groceries.factory('Seasonal', function() {

  var springFruit = [
    'Apricots',
    'Cherimoya',
    'Cherries (Barbados)',
    'Honeydew',
    'Jackfruit',
    'Limes',
    'Lychee',
    'Mango',
    'Melon (Bitter)',
    'Oranges',
    'Pineapple',
    'Strawberries'
  ];
  var summerFruit = [
    'Apricots',
    'Asian Pear',
    'Barbados Cherries',
    'Black Crowberries',
    'Black Currants',
    'Blackberries',
    'Blueberries',
    'Boysenberries',
    'Breadfruit',
    'Cantaloupe',
    'Casaba Melon',
    'Champagne Grapes',
    'Cherries',
    'Cherries, Sour',
    'Crenshaw Melon',
    'Durian',
    'Elderberries',
    'Figs',
    'Grapefruit',
    'Grapes',
    'Honeydew Melons',
    'Jackfruit',
    'Key Limes',
    'Limes',
    'Loganberries',
    'Longan',
    'Loquat',
    'Lychee',
    'Mulberries',
    'Nectarines',
    'Olallieberries',
    'Passion Fruit',
    'Peaches',
    'Persian Melon',
    'Plums',
    'Raspberries',
    'Sapodillas',
    'Sapote',
    'Strawberries',
    'Sugar Apple',
    'Tomatoes',
    'Watermelon'
  ];
  var fallFruit = [
    'Black Crowberries',
    'Cactus Pear',
    'Cherries, Barbados',
    'Apples',
    'Cranberries',
    'Feijoa',
    'Gooseberries, Cape',
    'Grapes',
    'Grapes, Muscadine',
    'Guava',
    'Huckleberries',
    'Jujube',
    'Key Limes',
    'Kumquats',
    'Passion Fruit',
    'Pear, All',
    'Persimmons',
    'Pineapple',
    'Pomegranate',
    'Quince',
    'Sapote',
    'Sharon Fruit',
    'Sugar Apple'
  ];
  var winterFruit = [
    'Cactus Pear',
    'Cardoon',
    'Cherimoya',
    'Clementines',
    'Dates',
    'Grapefruit',
    'Kiwifruit',
    'Mandarins',
    'Oranges',
    'Passion Fruit',
    'Pear',
    'Persimmons',
    'Pummelo',
    'Red Banana',
    'Red Currants',
    'Sharon Fruit',
    'Tangerines'
  ];

  var springVeggie = [
    'Artichokes',
    'Asparagus',
    'Asparagus, Purple',
    'Asparagus, White',
    'Beans, Fava',
    'Beans, Green',
    'Broccoli',
    'Cactus',
    'Chives',
    'Corn',
    'Endive, Belgian',
    'Fennel',
    'Fiddlehead Ferns',
    'Greens, Collard',
    'Greens, Mustard',
    'Greens, Spinach',
    'Greens, Swiss Cha.',
    'Lettuce, Butter',
    'Lettuce, Manoa',
    'Lettuce, Red Leaf',
    'Lettuce, Spring Baby',
    'Mushrooms, Morel ',
    'Onions, Vidalia',
    'Pea Pods',
    'Peas',
    'Peas, Snow ',
    'Radicchio',
    'Ramps',
    'Rhubarb',
    'Sorrel',
    'Squash, Chayote ',
    'Watercress'
  ];
  var summerVeggie = [
    'Beans, Chinese Lng',
    'Beans, Green',
    'Beans, Lima',
    'Beans, Winged',
    'Beets',
    'Corn',
    'Cucumbers',
    'Edamame',
    'Eggplant',
    'Endive',
    'Garlic',
    'Lettuce, Butter',
    'Lettuce, Manoa',
    'Okra',
    'Peas',
    'Peas, Sugar Snap',
    'Peppers, Bell',
    'Peppers, Jalapeno',
    'Potatoes, Yukon Gld',
    'Radishes',
    'Shallots',
    'Squash, Chayote',
    'Squash, Crooknose',
    'Squash, Summer',
    'Squash, Zucchini',
    'Tomatillo'
  ];
  var fallVeggie = [
    'Beans, Chinese Lng',
    'Black Salsify',
    'Broccoli',
    'Brussels Sprouts',
    'Cardoon',
    'Cauliflower',
    'Diakon Radish',
    'Endive',
    'Endive, Belgian',
    'Garlic',
    'Ginger',
    'Jerusalem Artichoke',
    'Kohlrabi',
    'Lettuce, Butter',
    'Mushrooms',
    'Peppers, Jalapeno',
    'Pumpkin',
    'Radicchio',
    'Squash, Acorn',
    'Squash, Buttercup',
    'Squash, Butternut',
    'Squash, Chayote',
    'Squash, Delicata',
    'Squash, Sweet Dumpling',
    'Sweet Potatoes',
    'Swiss Chard',
    'Turnips'
  ];
  var winterVeggie = [
    'Brussels Sprouts',
    'Chestnuts',
    'Collard Greens',
    'Endive, Belgian',
    'Kale',
    'Leeks',
    'Squash, Buttercup',
    'Squash, Delicata',
    'Squash, Sweet Dumpling',
    'Sweet Potatoes',
    'Turnips'
  ];

  return {
    springFruit: springFruit,
    summerFruit: summerFruit,
    fallFruit: fallFruit,
    winterFruit: winterFruit,
    springVeggie: springVeggie,
    summerVeggie: summerVeggie,
    fallVeggie: fallVeggie,
    winterVeggie: winterVeggie
  };
});